apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend-app
  template:
    metadata:
      labels:
        app: trend-app
    spec:
      containers:
      - name: trend-app
        image: kalaiyarasi15/trend-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: trend-app-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: trend-app
  ports:
    - port: 80
      targetPort: 3000
